feat: rework modpkg format
LeagueToolkit/league-toolkit pull request #24
Opened 2024-11-11 20:52 UTC by Crauzer

2024-11-11 21:33 UTC, Crauzer commented on crates/league-modpkg/src/read.rs
> +        if !layers.contains(&"base".to_string()) {
This check is not correct, need to fix

2024-11-11 21:53 UTC, alanpq requested changes

2024-11-11 21:53 UTC, alanpq commented on crates/league-modpkg/src/read.rs
> +        let current_pos = reader.seek(SeekFrom::Current(0))?;
I wouldn't assume the reader starts at 0. You could use the measure lib function but you'd have to pack/unpack all the fields as a tuple or mutate or something, so might be easier to just measure the cursor pos before reading anything.

2024-11-11 23:13 UTC, moonshadow565 commented on crates/league-modpkg/src/chunk.rs
> +        let layers_index = reader.read_u32::<LE>()?;
needs one more u32 to be properly aligned
if you want you can point that extra u32 into string table, making it comment or something else idk

2024-11-11 23:23 UTC, moonshadow565 commented on crates/league-modpkg/src/read.rs
> +        let mut layers = Vec::with_capacity(layers_size);
```suggestion
        let mut metadata = vec![_::default(); metadata_size];
        let mut signature = vec![_::default(); signature_size];
        let mut chunk_paths = vec![_::default(); chunk_paths_size];
        let mut wad_paths = vec![_::default(); wad_paths_size];
        let mut layers = vec![_::default(); layers_size];
```
Capacity only reserves space, we need to actually allocate those.

2024-11-11 23:26 UTC, moonshadow565 commented on crates/league-modpkg/src/read.rs
> +        let chunks = Self::read_chunks(reader, chunk_count)?;
i would appreciate if there was alignment check to make sure chunks are aligned to 8 here
not strictly required but it's a nice thing to do

2024-11-12 11:29 UTC, alanpq submitted a review, later dismissed

2024-11-12 15:30 UTC, Crauzer commented
btw I'm probably in favor of doing our own serialization for metadata and strings, there seem to be differences between msgpack libraries in how they handle enums for example, so I'd like to avoid potential issues there

2024-11-12 16:43 UTC, moonshadow565 commented
> btw I'm probably in favor of doing our own serialization for metadata and strings, there seem to be differences between msgpack libraries in how they handle enums for example, so I'd like to avoid potential issues there

what about having metadata and strings table being just chunks instead of dedicated fields?

2024-11-13 10:58 UTC, Crauzer commented
> what about having metadata and strings table being just chunks instead of dedicated fields?

Sure, I don't think it should cause too much trouble for the user

2024-11-13 12:42 UTC, Crauzer commented
This is how I will do layers.
Instead of
```rust
let layers_index = reader.read_u32::<LE>()?;
let _ = reader.read_u32::<LE>()?; // reserved
```
we need to have a `layers_hash: u64` which points into a HashMap of layer definitions that are stored in an additional chunk. We also need to specify a priority for each layer so we can resolve conflicts if 2 layers modify the same file.

2025-01-27 18:22 UTC, Crauzer commented
@moonshadow565 @alanpq starting this up again

2025-01-27 18:59 UTC, moonshadow565 commented
> @moonshadow565 @alanpq starting this up again

Been thinking about it, no need to overcomplicate it.
Just make the format simple as possible (maybe with binrw ?).
For signature checking we can just generate dedicated TOC + sha256 of real metadata that we sign instead.

2025-01-27 19:02 UTC, alanpq commented
+1 on the binrw/etc usage, since we own both sides we might as well keep it as boilerplate free as possible

2025-02-07 12:07 UTC, alanpq commented on crates/league-modpkg/src/read.rs
> +        let chunks = Self::read_chunks(reader, chunk_count)?;
with the binrw port this should (hopefully) be enforced

2025-02-07 12:17 UTC, alanpq commented
@Crauzer @moonshadow565 few breaking changes with the binrw port:
- `Modpkg`'s `metadata`, `chunk_paths` & `wad_paths` are no longer stored in the chunk map
- the strings inside of `ModpkgLicense` are null terminated now instead of len-prefixed (this feels better to me but can easily change it back)
- there might be more that I've either forgotten or missed, so I recommend poking around yourselves

2025-02-07 17:10 UTC, moonshadow565 commented on crates/league-modpkg/src/metadata.rs
> +    pub fn size(&self) -> usize {
There should be better way to do this with binrw

2025-02-07 17:10 UTC, moonshadow565 commented on crates/league-modpkg/src/metadata.rs
> +    pub fn size(&self) -> usize {
Same as  ModpkgMetadata::size

2025-02-07 19:21 UTC, alanpq commented on crates/league-modpkg/src/metadata.rs
> +    pub fn size(&self) -> usize {
As far as I know, we either do this or we use some custom String struct that impls BinWrite/Read (or we ask binrw to implement mapping inside an option somehow)

2025-02-07 19:46 UTC, moonshadow565 commented on crates/league-modpkg/src/metadata.rs
> +    pub fn size(&self) -> usize {
Why not just implement dummy Write that tracks the size and write metdata into it?

2025-02-07 21:12 UTC, alanpq commented on crates/league-modpkg/src/metadata.rs
> +    pub fn size(&self) -> usize {
Github mobile lied to me, thought this was a comment on the optional_string_write map stuff. There probably is a better way I just ported what already was there - I'll let @Crauzer decide what to replace it with

2025-02-13 08:16 UTC, Crauzer commented on crates/league-modpkg/src/metadata.rs
> +    pub fn size(&self) -> usize {
Honestly, I don't even see the point of this function existing now that we're using `binrw`. I think we can remove it. If needed, we can add it back using some other way as moon said.

2025-03-01 15:40 UTC, Crauzer commented
Going to merge this as it is, we can further refine the format as needed while I work on the mod project packer.

2025-03-01 15:41 UTC, merged